### PR TITLE
Corrected issue with UI locking on Android when StartPreview is called before Texture is available

### PR DESCRIPTION
**Pull request by jlinker7**
Switched StartPreview to rely on SurfaceTextureAvailable rather than null and switched to Task.Delay to avoid UI locking
Modified StopCamera to AbortCapture and Close to avoid errors.

### CODE REVIEW

**Comment by jlinker7** [comment]
Resolves #85

**Comment by hjam40** [comment]
Hi,

Thank you for your pull request. I can't pull it to the code because I'm working in local changes but I have implemented it in my code in another way:

while (textureView.SurfaceTexture == null || !textureView.IsAvailable) Thread.Sleep(100);

**Comment by jlinker7** [comment]
Implementing it this way does not quite work.  

My use case is I have a CameraView on a screen (it is technically hidden off screen, but this occurs even if i have it on the screen for testing).  That screen uses the camera feed to compare frames to detect motion.  If motion is detected it stops the CameraView on that page and loads another page with a camera view that displays the camera feed and looks for a face and then uses a face authentication program for authentication.

When the motion is detected and the second screen is called, if your StartCamera method is called before the Texture is available the app freezes.  If I changed your code to use await Task.Delay(100) (and change the method to async void) then it seems to work.

I have a couple of other small issues, but will create separate items for those if I find a way to fix them in your code (on my second screen I have to add a Task.Delay(800) before calling StartCameraAsync in my CamerasLoaded listener after i get the camera.  If I do not have the 800 ms delay (i tested it in 50  ms increments) then the preview loads grainy and terrible quality).

**Comment by jlinker7** [comment]
@hjam40 Following up to see if you saw my comment on your implementation?

**Pull request closed without merging**
